export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_SUCCESS = 'VALIDAR_FORMULARIO_SUCCESS';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_SUCCESS = 'AGREGAR_PRODUCTO_SUCCESS';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const COMENZAR_DESCARGA_PRODUCTOS_SUCCESS =
  'COMENZAR_DESCARGA_PRODUCTOS_SUCCESS';
export const COMENZAR_DESCARGA_PRODUCTOS_ERROR =
  'COMENZAR_DESCARGA_PRODUCTOS_ERROR';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_SUCCESS = 'ELIMINAR_PRODUCTO_SUCCESS';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';

export const OBTENER_EDITAR_PRODUCTO = 'OBTENER_EDITAR_PRODUCTO';
export const OBTENER_EDITAR_PRODUCTO_SUCCESS =
  'OBTENER_EDITAR_PRODUCTO_SUCCESS';
export const OBTENER_EDITAR_PRODUCTO_ERROR = 'OBTENER_EDITAR_PRODUCTO_ERROR';

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_SUCCESS = 'EDITAR_PRODUCTO_SUCCESS';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';
